import React, { useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import useSwerveStore from '../../store/useSwerveStore';
import { format } from 'date-fns';

function ssiLabel(ssi) {
    if (ssi >= 85) return { label: 'Optimal',  color: '#34d399' };
    if (ssi >= 70) return { label: 'Fair',      color: '#3b82f6' };
    if (ssi >= 55) return { label: 'Caution',   color: '#fbbf24' };
    if (ssi >= 30) return { label: 'Severe',    color: '#f97316' };
    return             { label: 'Critical',     color: '#ef4444' };
}

function fmtDate(ts) {
    try { return format(new Date(ts), 'MMM d, yyyy'); } catch { return '—'; }
}

export default function InsuranceReportModal() {
    const { ui, setUiState, savedRoutes, swerveScore } = useSwerveStore();
    const show = ui?.showInsuranceReport ?? false;

    // Build 90-day stats from saved routes
    const stats = useMemo(() => {
        const cutoff = Date.now() - 90 * 24 * 3600 * 1000;
        const recent = savedRoutes.filter((r) => r.savedAt > cutoff);
        const total = recent.length;
        if (!total) return null;

        const avgSsi = Math.round(recent.reduce((s, r) => s + (r.ssi || 0), 0) / total);
        const safeCount = recent.filter((r) => (r.ssi || 0) >= 70).length;
        const safePct = Math.round((safeCount / total) * 100);
        const optimalCount = recent.filter((r) => (r.ssi || 0) >= 85).length;
        const oldest = recent.reduce((min, r) => Math.min(min, r.savedAt), Date.now());

        return { total, avgSsi, safeCount, safePct, optimalCount, recent, oldest };
    }, [savedRoutes]);

    const handlePrint = () => {
        window.print();
    };

    const today = format(new Date(), 'MMMM d, yyyy');
    const { label: avgLabel, color: avgColor } = ssiLabel(stats?.avgSsi ?? 0);

    return (
        <AnimatePresence>
            {show && (
                <motion.div
                    key="insurance-modal"
                    className="absolute inset-0 z-[60] flex items-center justify-center p-4"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    style={{ background: 'rgba(0,0,0,0.75)', backdropFilter: 'blur(8px)' }}
                    onClick={(e) => { if (e.target === e.currentTarget) setUiState({ showInsuranceReport: false }); }}
                >
                    <motion.div
                        initial={{ opacity: 0, y: 24, scale: 0.97 }}
                        animate={{ opacity: 1, y: 0, scale: 1 }}
                        exit={{ opacity: 0, y: 24, scale: 0.97 }}
                        transition={{ type: 'spring', stiffness: 380, damping: 28 }}
                        className="relative w-full max-w-md rounded-[24px] overflow-hidden"
                        style={{
                            background: 'rgba(10,10,14,0.98)',
                            border: '1px solid rgba(255,255,255,0.10)',
                            boxShadow: '0 32px 80px rgba(0,0,0,0.7), inset 0 1px 0 rgba(255,255,255,0.06)',
                            maxHeight: '90vh',
                            overflowY: 'auto',
                        }}
                        id="insurance-report-content"
                    >
                        {/* Accent top bar */}
                        <div className="h-1 w-full" style={{ background: 'linear-gradient(90deg, #34d399, #3b82f6, #a78bfa)' }} />

                        <div className="p-6">
                            {/* Header */}
                            <div className="flex items-start justify-between mb-6">
                                <div>
                                    <div className="flex items-center gap-2 mb-1">
                                        <span className="text-xl">🛡️</span>
                                        <h2 className="text-white font-bold text-lg tracking-tight">Safe Driver Report</h2>
                                    </div>
                                    <p className="text-white/35 text-[11px]">Generated by Swerve · {today}</p>
                                </div>
                                <button
                                    onClick={() => setUiState({ showInsuranceReport: false })}
                                    className="p-2 rounded-xl text-white/25 hover:text-white/60 hover:bg-white/[0.06] transition-colors"
                                >
                                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                                    </svg>
                                </button>
                            </div>

                            {!stats ? (
                                <div className="text-center py-12">
                                    <p className="text-white/40 text-sm">No route history in the last 90 days.</p>
                                    <p className="text-white/25 text-[11px] mt-1">Complete routes to build your safe driver profile.</p>
                                </div>
                            ) : (
                                <>
                                    {/* Summary banner */}
                                    <div
                                        className="rounded-2xl p-4 mb-5"
                                        style={{ background: `${avgColor}12`, border: `1px solid ${avgColor}30` }}
                                    >
                                        <div className="flex items-center justify-between">
                                            <div>
                                                <p className="text-white/50 text-[10px] uppercase tracking-wider mb-1">90-Day Average SSI</p>
                                                <div className="flex items-baseline gap-2">
                                                    <span className="text-4xl font-mono font-bold" style={{ color: avgColor }}>{stats.avgSsi}</span>
                                                    <span className="text-base font-semibold" style={{ color: avgColor }}>{avgLabel}</span>
                                                </div>
                                            </div>
                                            <div
                                                className="w-16 h-16 rounded-2xl flex items-center justify-center"
                                                style={{ background: `${avgColor}20` }}
                                            >
                                                <svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke={avgColor}>
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                                                </svg>
                                            </div>
                                        </div>
                                    </div>

                                    {/* Stats grid */}
                                    <div className="grid grid-cols-3 gap-3 mb-5">
                                        {[
                                            { label: 'Total Trips', value: stats.total, color: '#a78bfa' },
                                            { label: 'Safe Trips', value: `${stats.safePct}%`, sub: `${stats.safeCount} routes ≥ 70`, color: '#22d3ee' },
                                            { label: 'Optimal Trips', value: stats.optimalCount, sub: 'SSI ≥ 85', color: '#34d399' },
                                        ].map(({ label, value, sub, color }) => (
                                            <div
                                                key={label}
                                                className="rounded-xl p-3 text-center"
                                                style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.06)' }}
                                            >
                                                <p className="text-white/30 text-[9px] uppercase tracking-wider mb-1">{label}</p>
                                                <p className="font-mono font-bold text-xl" style={{ color }}>{value}</p>
                                                {sub && <p className="text-white/25 text-[8px] mt-0.5">{sub}</p>}
                                            </div>
                                        ))}
                                    </div>

                                    {/* Swerve Score */}
                                    <div
                                        className="rounded-xl p-3 mb-5 flex items-center justify-between"
                                        style={{ background: 'rgba(252,211,77,0.06)', border: '1px solid rgba(252,211,77,0.12)' }}
                                    >
                                        <div>
                                            <p className="text-amber-300/60 text-[9px] uppercase tracking-wider">Swerve Score</p>
                                            <p className="text-amber-300 font-bold text-lg tabular-nums">{(swerveScore?.total ?? 0).toLocaleString()} pts</p>
                                        </div>
                                        <div className="text-right">
                                            <p className="text-amber-300/60 text-[9px] uppercase tracking-wider">Streak</p>
                                            <p className="text-amber-300 font-bold text-lg">{swerveScore?.currentStreak ?? 0} days 🔥</p>
                                        </div>
                                    </div>

                                    {/* Recent trips */}
                                    <div className="mb-5">
                                        <p className="text-white/25 text-[9px] uppercase tracking-widest mb-2">Recent Trips (90 days)</p>
                                        <div className="space-y-1.5 max-h-40 overflow-y-auto pr-1">
                                            {stats.recent.slice(0, 20).map((r, i) => {
                                                const { color } = ssiLabel(r.ssi);
                                                return (
                                                    <div
                                                        key={r.id ?? i}
                                                        className="flex items-center justify-between py-2 px-3 rounded-xl"
                                                        style={{ background: 'rgba(255,255,255,0.03)' }}
                                                    >
                                                        <div className="min-w-0 flex-1">
                                                            <p className="text-white/70 text-[10px] font-medium truncate">{r.dest || r.start || 'Route'}</p>
                                                            <p className="text-white/25 text-[9px]">{fmtDate(r.savedAt)}</p>
                                                        </div>
                                                        <span className="text-[11px] font-bold tabular-nums ml-3" style={{ color }}>{r.ssi}</span>
                                                    </div>
                                                );
                                            })}
                                        </div>
                                    </div>

                                    {/* Insurance CTA */}
                                    <div
                                        className="rounded-xl p-4 mb-5"
                                        style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.06)' }}
                                    >
                                        <p className="text-white/60 text-[11px] leading-relaxed">
                                            Share this report with your insurance agent to ask about safe-driver telematics discounts.
                                            Swerve's weather-adjusted SSI score demonstrates driving behavior in real conditions —
                                            including rain, ice, and storm events — unlike basic telematics that only track speed and braking.
                                        </p>
                                    </div>

                                    {/* Print / share */}
                                    <motion.button
                                        onClick={handlePrint}
                                        whileHover={{ scale: 1.02 }}
                                        whileTap={{ scale: 0.97 }}
                                        className="w-full py-3 rounded-xl font-bold text-sm text-white flex items-center justify-center gap-2"
                                        style={{
                                            background: 'linear-gradient(135deg, rgba(52,211,153,0.9), rgba(16,185,129,0.85))',
                                            boxShadow: '0 4px 20px rgba(52,211,153,0.25), inset 0 1px 0 rgba(255,255,255,0.15)',
                                        }}
                                    >
                                        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
                                        </svg>
                                        Print / Save as PDF
                                    </motion.button>
                                </>
                            )}

                            {/* Footer */}
                            <p className="text-white/15 text-[9px] text-center mt-4 leading-relaxed">
                                Generated by Swerve Navigation · Weather Intelligence Navigation Platform
                                · Data covers the 90 days prior to {today}
                            </p>
                        </div>
                    </motion.div>
                </motion.div>
            )}
        </AnimatePresence>
    );
}
